// default package
// Generated 2013-05-27 13:40:06 by Hibernate Tools 3.4.0.CR1
package data;
import java.util.Calendar;
import java.util.List;

import data.interfaces.ISample;

/**
 * Matches generated by hbm2java
 */
public class Matches implements java.io.Serializable , ISample{

	private int id;
	private Calendar Date;
	private String City;
	private String Country;
	
	public Matches() {
	}

	public Matches(int id) {
		this.id = id;
	}

	public Matches(int id, Calendar Date, String City, String Country) {
		this.id = id;
		this.Date = Date;
		this.City = City;
		this.Country = Country;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Calendar getDate() {
		return this.Date;
	}

	public void setDate(Calendar Date) {
		this.Date = Date;
	}

	public String getCity() {
		return this.City;
	}

	public void setCity(String City) {
		this.City = City;
	}

	public String getCountry() {
		return this.Country;
	}

	public void setCountry(String Country) {
		this.Country = Country;
	}

	@Override
	public List<String> getAttributeNames() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public Object getValue(String attrName) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public Class<?> getValueType(String attrName) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public List<Object> getValues() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public boolean setValue(String attrName, Object v) {
		// TODO Auto-generated method stub
		return false;
	}

}
